/game_log(category, text)
	..()
	testing("[category], [text]")
	if(category in list("ADMIN", "GAME", "SAY", "WHISPER", "EMOTE", "OOC"))
		testing("LPUSHed")
		redis_client.lpush(category, "[game_id]@[text]")
