/mob/living/carbon/superior_animal/adjustBruteLoss(damage)
    ..()
    if(stance == HOSTILE_STANCE_ATTACK)
        for(var/mob/living/carbon/superior_animal/SA in view(1))
            SA.target_mob = SA.findTarget()